### ISSUE TITLE
tree_reader fails if there is a comma in labels

### ISSUE THREAD

**Issue by cjgrady** [FePhyFoFum/biotaphy_scripts#1]
If there is a comma in a taxon label (example: 'Hypochrosis baenzigeri Inoue, 1982'), the tree_reader will crash.

Traceback (most recent call last):
  File "create_stats_matrices.py", line 84, in <module>
    tree = read_tree_string(tree_newick)
  File "/home/cjgrady/git/biotaphy_scripts/tree_reader.py", line 61, in read_tree_string
    curnode.label = name
AttributeError: 'NoneType' object has no attribute 'label'

It seems to be splitting the label into two.

I am submitting a pull request that has a an example tree (Geometridae.nex)

**Comment by blackrim** [comment]
gotcha. will this be common or will things generally have gbif/ottids? i will update the tree_reader regardless, and did the pull request

**Comment by blackrim** [comment]
it should take standard newick now (if there is a quote or double quote, then the whole name is read until the end quote). i think that should do it but reopen if not e5b4e5d
